name: rpc_dart_transports
description: RPC Dart Transports library
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  rpc_dart: ^2.0.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  args: ^2.6.0
  http2: ^2.3.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
