version = 1

[[annotations]]
path = [
    "lib/**",
    "example/**",
    "test/**",
    "benchmark/**",
]
SPDX-FileCopyrightText = "2025 Karim \"nogipx\" Mamatkazin <nogipx@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "docs/**",
    "logo/**",
    "benchmark_results/**",
    "**/*.md",
    "**/*.yaml",
    "**/*.yml",
    "justfile",
    "pubspec.yaml",
    "analysis_options.yaml",
    ".gitignore",
    ".pubignore",
    ".cursorignore",
    ".fvmrc",
    ".cursor/**",
]
SPDX-FileCopyrightText = "2025 Karim \"nogipx\" Mamatkazin <nogipx@gmail.com>"
SPDX-License-Identifier = "MIT"
