name: rpc_dart_transports
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  rpc_dart:
    path: ../rpc_dart

# Add regular dependencies here.
dependencies:
  rpc_dart:
    git:
      url: https://github.com/nogipx/rpc_dart.git
      ref: main
      path: rpc_dart

  uuid: ^4.5.1
  web_socket_channel: ^2.4.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
