name: rpc_dart
description: gRPC-inspired library built on pure Dart, Backend-for-Domain (BfD)
version: 1.0.1
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://github.com/nogipx/rpc_dart
issue_tracker: https://github.com/nogipx/rpc_dart/issues

funding:
  - https://liberapay.com/nogipx

example: example/README.md

topics:
  - rpc
  - grpc
  - streaming
  - bidirectional
  - backend-for-domain

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

