name: rpc_dart
description: gRPC-inspired library built on pure Dart, Backend-for-Domain (BFD)
version: 1.0.1
repository: https://github.com/nogipx/rpc_dart.git
homepage: https://github.com/nogipx/rpc_dart
issue_tracker: https://github.com/nogipx/rpc_dart/issues
funding:
  - https://liberapay.com/nogipx

topics:
  - rpc
  - grpc
  - streaming
  - bidirectional
  - backend-for-domain

environment:
  sdk: ">=3.0.0"
  
dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2

