name: rpc_example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  rpc_dart_example: bin/main.dart

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  protobuf: ^4.0.0
  fixnum: ^1.1.1

  rpc_dart:
    git:
      url: https://github.com/nogipx/rpc_dart.git
      ref: main
      path: rpc_dart

  rpc_dart_transports:
    git:
      url: https://github.com/nogipx/rpc_dart.git
      ref: main
      path: rpc_dart_transports

dependency_overrides:
  rpc_dart:
    path: ../rpc_dart
    
  rpc_dart_transports:
    path: ../rpc_dart_transports

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  protoc_plugin: ^22.2.0
  
